"""Hessisch - Rhein-Main, Frankfurter Färbung."""

from __future__ import annotations

from . import muster

KEY = "hessisch"
NAME = "Hessisch"
BESCHREIBUNG = (
    "Rhein-Main-Hessisch, wie man es in Frankfurt und Umgebung hört. "
    "Gemütlich, mit einem 'Ei gude' hier und da."
)
LANG_ID = "HESSEN"

TEXTE = {
    # --- Netzwerk ---------------------------------------------------
    1: "Isch wart uff des Netzwerk.",
    2: "Mit'm WLAN hat's net geklappt. Guck der mol des Passwort aa.",
    3: "Isch komm net uff de Server. Guck der mol dei Netzwerk aa.",
    5: "Netzwerk basst, isch bin dribbe.",
    6: "Mit'm Netzwerk hat's net geklappt. Probier's später nochemol.",

    # --- Reinigung ---------------------------------------------------
    7: "Ei gude, dann geht's los. Isch fang aa zu sauge.",
    8: "Isch mach den oane Fleck sauber.",
    9: "Die geplante Reinigung geht jetzt los.",
    10: "Isch mach weider, wo isch uffgehört hab.",
    12: "Fertisch. Alles sauber.",
    56: "Isch mach des Zimmer sauber.",
    57: "Isch mach die Zone sauber.",
    58: "Isch mach mei Arbeit weider.",
    61: "Isch fang aa zu wische.",
    62: "Du steuerst misch jetzt selber.",
    82: "Isch mal jetzt e Kart vun de Wohnung.",
    84: "Die Kart is fertisch.",
    105: "Uff geht's, isch fang aa.",
    126: "Isch fang aa zu sauge.",
    137: "Isch saug weider.",
    138: "Isch wisch weider.",
    139: "Isch komm zurück.",
    143: "Fertisch. Do sieht's jetzt sauber aus.",
    144: "Gewischt hab isch aa schon.",
    164: "So, des war's. Feierohmd.",
    433: "Isch mach noch e Extrarund.",
    434: "Die Extrarund is fertisch, isch mach normal weider.",

    # --- Akku und Laden ----------------------------------------------
    13: "Isch fahr heim zum Uffladde.",
    14: "Mei Batterie is bald leer. Isch fahr heim zum Ladde un mach dann weider.",
    17: "Stell misch bitte widder uff die Station.",
    18: "Isch lad grad uff.",
    20: "Mei Batterie is bald leer.",
    21: "Batterie leer. Isch schalt misch jetzt aus.",
    47: "Isch fang aa zu ladde.",
    48: "Batterie is schwach, isch fahr zur Station.",
    50: "Mit'm Ladde stimmt was net. Mach mer die Kontakte sauber.",
    301: "Isch lad grad uff.",
    302: "Isch bin grad am Schaffe.",

    # --- Station und Wischen -----------------------------------------
    106: "Isch wasch mei Wischtuch.",
    107: "Isch trockne mei Wischtücher.",
    110: "Isch saug mein Staab aus.",
    111: "Mir fehle die Wischtücher. Mach se mer bitte draa.",
    112: "Stell misch erst emol in die Station.",
    113: "Fertisch. Mach bitte de Schmutzwassertank leer.",
    114: "Die Wischtücher sinn draa.",
    115: "Die Wischtücher sinn runner.",
    148: "Isch fahr zur Station un mach misch selber sauber.",
    169: "Die Wischtücher sinn trocke.",
    177: "Isch fahr los.",
    179: "Wischtuch is sauber. Aber's Frischwasser geht mer aus.",
    181: "Mir geht's Wasser aus. Füll mer bitte nach.",
    186: "Guck der bitte de Frischwassertank aa.",
    187: "Des dauert so fünf bis zehn Minudde.",
    318: "Mei Wischtuch is widder sauber.",
    636: "Mei Wischtuch is arg dreckisch. Isch muss zur Station.",

    # --- Fehler und Wartung ------------------------------------------
    35: "Mit de Hauptbürst stimmt was net. Mach se mer sauber.",
    36: "Mit de Seidebürst stimmt was net. Mach se mer sauber.",
    37: "Mit'm rechte Rad stimmt was net.",
    38: "Mit'm linke Rad stimmt was net.",
    40: "Ei verrescht, isch häng fest. Machst misch bitte frei?",
    42: "Guck der bitte mein Filder aa.",
    43: "Mit meim Stoßbügel stimmt was net. Drück emol sanft druff.",
    44: "Do stimmt was net. Guck bitte in de Aaleitung nach.",
    52: "Isch steh schief. Stell misch bitte grad hie.",
    66: "Mei Filder is hie. Tausch'n bitte aus.",
    67: "Die Seidebürst is hie. Tausch se bitte aus.",
    68: "Die Hauptbürst is hie. Tausch se bitte aus.",
    91: "De Frischwassertank fehlt. Setz'n bitte nei.",
    93: "Zu wenisch Wasser drin. Füll bitte nach.",
    97: "Do fehlt de Staabbeutel.",
    102: "De Staabbeutel is voll oder de Kanal is verstopft.",
    156: "Mei Wischtuch is net draa.",
    166: "Do hat sisch was in mei Wischtuch gewickelt. Mach's bitte weg.",
    267: "Mei Sensore sinn dreckisch. Mach se mer bitte sauber.",
    331: "Alles in Ordnung. Isch hab nix gefunne.",
    332: "Isch hab en Fehler gefunne. Guck emol in de App nach.",
    426: "Isch bin abgerutscht un häng fest. Isch probier's weider.",
    437: "Basst widder. Drück uff Start, dann geht's weider.",
    441: "Do hat sisch was um die Hauptbürst gewickelt. Mach's bitte sauber.",
    442: "Do hat sisch was um die Seidebürst gewickelt.",
    443: "Um mei Räder hat sisch was gewickelt.",
    444: "Stell misch bitte uff e freie Fläch, dann fang isch aa.",
    445: "Mei Wischtuch is mer runnergefalle. Guck emol in de Näh.",
    446: "Am Wischtuchhalder hängt was draa.",
    447: "Die Station hat kaan Strom. Guck bitte emol nach.",
    448: "De Schmutzwassertank fehlt. Setz'n bitte nei.",
    449: "Uff'm Teppisch fang isch net aa. Stell misch uff de Hartbodde.",
    454: "Zu wenisch Wasser im Tank. Füll mer bitte nach.",
    455: "De Frischwassertank sitzt net rischtisch drin.",
    456: "De Schmutzwassertank is voll oder er fehlt.",
    458: "De Staabbeutel sitzt net rischtisch.",
    460: "De Geruchsfilder is uffgebraucht. Tausch'n bitte aus.",
    639: "Do fehlt de Filder vum Waschbrett.",
    658: "De Kalkschutz is uffgebraucht. Tausch'n bitte aus.",

    # --- Wegfindung ---------------------------------------------------
    30: "Isch guck grad, wo isch bin.",
    31: "Isch waaß net, wo isch bin. Isch fang halt neu aa.",
    45: "Isch bin do!",
    149: "Do komm isch net hie. Räum bitte weg, was im Weg steht.",
    151: "Mei Weg is verstellt. Räum bitte was weg.",
    153: "Isch steh in ere Sperrzon. Nimm misch do bitte raus.",

    # --- Bedienung -----------------------------------------------------
    26: "Isch setz misch zurück uff die Werkseinstellung.",
    27: "Isch mach e Update. Dauert fünf Minudde. Bitte net ausschalte.",
    28: "Des Update hat geklappt.",
    29: "Des Update hat net geklappt. Probier's später nochemol.",
    116: "Die Kindersischerung is aa. Die Knöpp sinn gesperrt.",
    117: "Die Kindersischerung is aus.",
    162: "Die Kamera is aa.",
    329: "Isch test misch grad selber. Nimm misch net vun de Station runner.",
    421: "Ei gude. Ab jetzt babbel isch Hessisch mit der.",
    632: "De Sprachwechsel dauert e halb Minudd.",
    633: "De Sprachwechsel hat net geklappt.",

    # --- Sprachassistent ------------------------------------------------
    190: "Basst, isch fang aa zu sauge.",
    191: "Basst, isch saug un wisch.",
    192: "Basst, isch wisch.",
    193: "Basst, isch saug.",
    221: "Basst schon.",
    246: "Isch bin do hinne!",
    247: "Des hab isch jetzt net verstanne.",
    508: "Isch babbel lauder.",
    509: "Isch babbel leiser.",
    510: "Gut, isch hör uff für heut.",
    515: "Sei so gut un heb emol die Füß.",
}

# --------------------------------------------------------------------------
# Schematische Ansagen (Akkustand 0-100 %, Raumbestaetigungen).
# Werden aus diesen Mustern erzeugt statt 117-mal von Hand geschrieben.
# --------------------------------------------------------------------------

AKKU_MUSTER = 'Akku is bei {p} Prozent.'
RAUM_MUSTER = 'Basst, isch mach {raum} sauber.'
RAUM_NAMEN = {
    'wohnzimmer': 'es Wohnzimmer',
    'schlafzimmer': 'es Schlafzimmer',
    'hauptschlafzimmer': 'es Hauptschlafzimmer',
    'gaestezimmer': 'es Gästezimmer',
    'arbeitszimmer': 'es Arbeitszimmer',
    'kueche': 'die Küch',
    'esszimmer': 'es Esszimmer',
    'bad': 'es Bad',
    'balkon': 'de Balkon',
    'flur': 'de Flur',
    'hauswirtschaftsraum': 'die Waschkisch',
    'abstellraum': 'die Abstellkammer',
    'salon': 'de Salon',
    'buero': 'es Büro',
    'gym': 'de Fitnessraum',
    'freizeitraum': 'de Freizeitraum',
}

TEXTE.update(muster.erzeuge(AKKU_MUSTER, RAUM_MUSTER, RAUM_NAMEN))

# --------------------------------------------------------------------------
# Vollstaendige Abdeckung: die restlichen Ansagen des X50 Ultra Complete.
# Nummern ohne Sprachinhalt (Klaenge, Tierlaute) bleiben im Original; die
# Nummern-Umsetzung des Modells versorgt 856, 858, 859, 863 und 864.
# --------------------------------------------------------------------------

TEXTE.update({
    # --- Netzwerk -----------------------------------------------------
    4: "Isch hab de Netzwerkmodus verlasse.",
    304: "Des Netzwerk is verbunne.",
    306: "Des hab isch net verstanne. Rischt erst des Netzwerk ei.",
    313: "De Empfang is schlecht. Stell misch woanners hie.",
    377: "Des Netzwerk lässt sisch net eirischte. Frag beim Kundedienst nach.",
    378: "Des Passwort stimmt net. Rischt des Netzwerk nochemol ei.",
    379: "Isch find kaa WLAN. Nimm des Zwaakommavier-Gigahertz-Netz.",
    380: "Isch hab kaa IP-Adress kriegt. Guck emol in dein Router.",
    381: "Isch komm net uff de Server. Frag beim Kundedienst nach.",
    382: "Isch komm net ins Netz. Guck, ob dei Internet läft.",
    383: "Des Netzwerk lässt sisch net eirischte. Frag beim Kundedienst nach.",
    385: "Isch verbinn misch grad mitm Netzwerk.",

    # --- Reinigung ----------------------------------------------------
    11: "Isch mach e Paus.",
    54: "Positionierung basst, isch saug weider.",
    55: "Positionierung basst, isch fahr weider zur Station.",
    64: "Positionierung hat net geklappt. Isch fahr zur Station.",
    65: "Isch fahr weider zur Station.",
    77: "Stell misch uff en Hartbodde, do fang isch aa.",
    83: "Isch mal weider aa de Kart.",
    85: "Positionierung basst, isch mal weider.",
    86: "Positionierung hat net geklappt. Isch fang mitm Male neu aa.",
    127: "Isch mach de Fleck sauber.",
    128: "Isch wisch de Fleck.",
    129: "Die geplante Reinigung geht los.",
    130: "Die geplante Kartierung geht los.",
    133: "Isch mach die ausgesuchte Zimmer sauber.",
    134: "Isch wisch die ausgesuchte Zimmer.",
    135: "Isch mach die Zone sauber.",
    136: "Isch wisch die Zone.",
    145: "Positionierung basst, isch saug weider.",
    146: "Positionierung basst, isch mal weider.",
    150: "Do komm isch net hie. Nimm bitte die Sperrzone weg.",
    152: "Mei Weg is verstellt. Nimm die Sperrzone weg oder stell misch woanners hie.",
    163: "Isch guck grad mit de Kamera.",
    171: "Die schlaue Hindernisumfahrung is aa.",
    172: "Die schlaue Hindernisumfahrung is aus.",
    257: "Die Kameraiwerwachung is aus.",
    280: "Isch fang mit de eigestellte Reinigung aa.",
    321: "Isch fang mitm grindlische Fleckewische aa.",
    344: "Basst, isch saug erst un wisch dann.",
    362: "Des Wischtuch sitzt net risch. Isch saug stattdesse nur.",
    363: "Des Sauge is fertisch, jetzt wisch isch.",
    366: "Do is e Fleck, isch mach en sauber.",
    367: "Basst, isch mach de Fleck sauber.",
    368: "Do is e Fleck. Isch mach en sauber, wenn isch gewasche hab.",
    369: "Basst, isch mach do sauber.",
    424: "Isch waaß net, wo isch bin. Stell misch uff e freie Fläch un fang neu aa.",
    435: "Isch fahr aus dem Bereisch raus.",
    450: "In ere Sperrzon fang isch net aa. Stell misch woanners hie.",
    451: "Im versteckte Bereisch fang isch net aa. Stell misch woanners hie.",
    677: "Do komm isch net hie. Nimm die Sperrzone oder die Schwelle weg.",
    678: "Mei Weg is verstellt. Nimm die Sperrzone oder die Schwelle weg.",
    679: "Isch steh in ere Sperrzon. Nimm misch do bitte raus.",
    680: "Isch mal erst e Kart, dann mach isch sauber.",
    681: "Basst, isch mach weider.",

    # --- Akku und Laden ------------------------------------------------
    19: "Nimm misch vun de Station, bevor de misch ausmachst.",
    25: "De Akku is zu schwach für die geplante Reinigung.",
    87: "Batterie schwach, isch fahr zur Station.",
    303: "Isch ruh misch grad aus.",
    307: "Isch lad grad uff.",

    # --- Fehler und Wartung --------------------------------------------
    34: "Do fehlt e Deil. Setz es bitte ei.",
    39: "Mei Räder hänge in de Luft. Mach die Absturzsensore sauber.",
    41: "Mei Räder hänge in de Luft. Stell misch woanners hie.",
    71: "Guck emol, ob am Laser-Abstandssensor ebbes klemmt.",
    72: "Die Abdeckung vum Lasersensor klemmt.",
    73: "Mitm Kantesensor stimmt was net.",
    75: "De Filder is feucht oder verstopft.",
    81: "Mitm Teppischsensor stimmt was net.",
    108: "Mitm Wasserstand vum Waschbrett stimmt was net. Mach es sauber.",
    109: "Mitm Schmutzwassertank stimmt was net. Guck, ob er drin un leer is.",
    118: "Die Knöpp sinn gesperrt. Halt die Tast an de Station gedrückt.",
    142: "Des Wischtuch is hie. Tausch es bitte aus.",
    173: "Tausch bitte des Silberione-Modul aus.",
    244: "Die Reinigungsmittelflasch is dro.",
    245: "Mehr Karte gehe net. Lösch bitte aane in de App.",
    296: "Guck emol, ob de Schmutzwassertank voll is.",
    297: "Die Reinigungsmittelflasch is dro. Wenn de se noch nie benutzt hast, guck in de App.",
    298: "Isch mach des Waschbrett sauber.",
    299: "Die Reinigungsmittelflasch un des Nachfüllmodul sinn dro.",
    300: "Des Zubehör kenn isch net.",
    312: "Iwer des Zubehör waaß isch nix. Tausch es aus, wenn es hie is.",
    315: "Des Wischtuch is net in de Station. Leg es nei un probier nochemol.",
    316: "In de Station liegt schon e Wischtuch.",
    319: "Des Wischtuch is net runnergange. Nimm es vun Hand ab.",
    320: "Des Wischtuch is net drogange. Mach es vun Hand dro.",
    330: "Wart, bis de Selbsttest fertisch is.",
    355: "Zu wenisch Wasser. Füll de Frischwassertank nach.",
    356: "De Fehler is noch do. Die geplante Reinigung is abgesagt.",
    384: "Im automatische Wassermodul is kaa Wasser.",
    388: "Do derf isch net hie. Stell misch woanners hie.",
    389: "De Laser fährt net runner. Guck, ob ebbes klemmt.",
    390: "De Laser fährt net ruff. Guck, ob ebbes klemmt.",
    391: "Stell misch uff e freie Fläch, bevor es losgeht.",
    392: "Im Clean-Genius-Modus lässt sisch des net eistelle.",
    438: "De Stoßbügel klemmt. Drück emol sanft druff.",
    439: "Die Laserabdeckung klemmt. Drück emol sanft druff.",
    440: "E Rad hängt in de Luft. Stell misch uff e freie Fläch.",
    452: "Mitm Teppischsensor stimmt was net. Dreh misch um un butz des weiße Loch.",
    453: "Mitm Kantesensor stimmt was net. Butz misch rechts aa.",
    457: "De Schmutzwassertank is voll oder net drin. Guck emol nach.",
    459: "De Wischtuchhalder sitzt net risch. Guck emol nach.",
    663: "Mitm Wasserstand im Waschbrett stimmt was net. Mach es sauber.",
    673: "Um mei Beinsche hat sisch villeischt ebbes gewickelt. Mach es sauber.",

    # --- Basisstation ---------------------------------------------------
    46: "Roboter un Handy sinn verbunne.",
    59: "Die Kart is fertisch. Nimm de Wassertank raus.",
    140: "E neue Umgebung. Isch fahr zur Station.",
    188: "Isch dock automatisch aa.",
    209: "Basst, isch fahr zur Station un wasch mei Wischtuch.",
    210: "Isch wasch die Wischtücher.",
    211: "Aussauge geht nur, wenn isch in de Station steh.",
    212: "Basst, isch saug misch aus.",
    213: "Trockne geht nur, wenn isch in de Station steh.",
    214: "Isch trockne grad.",
    215: "Basst, isch fang mitm Trockne aa.",
    216: "Do muss erst des Wischtuch dro.",
    278: "Basst, des Trockne is fertisch.",
    349: "Guck, dass die Station Strom hat, un stell misch druff.",
    350: "Isch fang mitm Eirischte vun de Station aa.",
    351: "Die Station is eigerischt.",
    352: "Des Eirischte hat net geklappt. Guck in de App nach.",
    360: "Isch lass des Wasser ausm Tank.",
    361: "Des Wasser is draußt.",
    371: "Nimm bitte des Waschbrett raus.",
    372: "Des Frischwasser läft ei.",
    373: "Des Wasser is drin. Wart zehn Sekunde, dann geht es weider.",
    374: "Butz de Bodde vun de Station mit ere Bürst oder eme Tuch.",
    375: "Schieb de Dreck zum Aussauge hie. Des dauert e bissi.",
    376: "Des Aussauge is fertisch. Butz des Waschbrett extra un setz es wieder ei.",
    396: "Isch mach des Wassermodul leer. Des dauert e bissi.",
    397: "Des Wasser is owwe un unne draußt.",
    398: "Die Kart is fertisch. Guck se der in de App aa un stell misch zurück.",
    399: "De Test is fertisch. Stell misch zurück uff die Station.",
    400: "Die Selbstreinigung is fertisch. Stell misch jetzt uff des risch Stockwerk.",
    401: "Stell misch uff die Station, dann fang isch mit de Selbstreinigung aa.",
    478: "Wenn isch gewasche hab, mach isch mitm Sauge weider.",
    479: "Basst, fang dei Arbeit neu aa.",
    480: "Füll genug Wasser ei, dass es fürs Nächste reischt.",
    481: "Isch mach de Handstaabsauger leer.",
    482: "Isch mach de Handstaabsauger leer. Misch selbst saug isch dann aus.",
    483: "Isch mach de Handstaabsauger leer. Des Wischtuch wasch isch dann.",
    484: "Isch mach de Handstaabsauger leer. Gesaugt werd dann.",
    485: "Isch saug misch grad aus. De Handstaabsauger kommt dann.",
    486: "Isch wasch grad des Wischtuch. De Handstaabsauger kommt dann.",
    487: "Guck, dass isch in de Station steh.",
    638: "Isch saug misch weider aus.",
    661: "Isch mach des Waschbrett sauber. Des dauert e knapp Minudd.",
    662: "Isch mach elektrolysiertes Wasser zum Butze.",

    # --- Sprachassistent -------------------------------------------------
    194: "Isch bin schon am Sauge.",
    195: "Basst, isch mach des Zimmer sauber. Guck, dass die Tür uff is.",
    196: "Basst, isch saug de Bodde. Guck, dass die Tür uff is.",
    197: "Basst, isch wisch de Bodde. Guck, dass die Tür uff is.",
    198: "Basst, isch saug un wisch. Guck, dass die Tür uff is.",
    199: "Des Zimmer kenn isch net. Guck in de App, wie es haaßt.",
    200: "Machs gut.",
    201: "Basst, isch mach weider.",
    202: "Basst, isch hör uff un fahr zum Lade.",
    203: "Basst, isch fahr zum Lade.",
    204: "Basst, isch fang mitm Male aa. Mach alle Türe uff.",
    205: "Basst, isch fahr vun de Station runner.",
    206: "Basst, isch guck, wo de bist.",
    207: "Isch find disch net. Stell disch in mei Sischtweit.",
    208: "Do bist de ja. Isch komm sauge.",
    217: "Mehr Saugkraft geht net.",
    218: "Wenischer Saugkraft geht net.",
    219: "Mehr Wasser geht net.",
    220: "Wenischer Wasser geht net.",
    222: "Saugstuf leis.",
    223: "Saugstuf normal.",
    224: "Saugstuf stark.",
    225: "Saugstuf Turbo.",
    226: "Des Wischtuch is leischt feucht.",
    227: "Des Wischtuch is feucht.",
    228: "Des Wischtuch is nass.",
    229: "Heut is",
    230: "Heut is de aanunzwanzischste Februar zwaadausendzwaaunzwanzisch.",
    231: "Heut is Montag.",
    232: "Heut is Dienstag.",
    233: "Heut is Mittwoch.",
    234: "Heut is Donnerstag.",
    235: "Heut is Freidag.",
    236: "Heut is Samstag.",
    237: "Heut is Sonntag.",
    238: "Basst, isch hör uff.",
    248: "Des Wischtuch fehlt. Mach es dro un probier nochemol.",
    249: "Isch schaff grad. Mach des erst fertisch, dann geht es.",
    250: "Isch bin grad im Wischmodus. Stell bitte um.",
    251: "Isch bin grad im Saugmodus. Stell bitte um.",
    252: "Fertisch. Isch bin aus de eigestellte Reinigung raus.",
    253: "Lauder geht net.",
    254: "Leiser geht net.",
    255: "Des geht nur mit eigeschalteter Hindernisumfahrung.",
    258: "Isch fang aa rumzufahre.",
    259: "Isch fahr zu dere Stell hie.",
    260: "Isch fahr weider rum.",
    261: "Isch fahr weider zu dere Stell.",
    262: "Isch waaß net, wo isch bin.",
    266: "Tausch bitte des Reinigungsmittel aus.",
    269: "Probier nochemol, wenn isch fertisch bin.",
    275: "Des kenn isch net. In de App stehe alle Sprachbefehle.",
    276: "Des mach isch grad net.",
    277: "Basst, isch komm un mach do sauber.",
    279: "Isch saug grad. Mach des erst fertisch un probier nochemol.",
    281: "Isch saug misch grad aus. Probier gleisch nochemol.",
    282: "Isch wasch grad mei Wischtuch. Probier gleisch nochemol.",
    283: "Isch steh net in de Station. Probier später nochemol.",
    284: "Basst, isch hör uff un komm sauge.",
    285: "Bleib kurz stehe, isch guck wo de bist.",
    286: "Do brauch isch erst e Kart.",
    287: "Basst, jetzt is leis.",
    288: "Basst, jetzt is normal.",
    289: "Basst, jetzt is stark.",
    290: "Basst, jetzt is Turbo.",
    291: "Basst, jetzt is leischt feucht.",
    292: "Basst, jetzt is nass.",
    293: "Aaruf sinn aa.",
    294: "Aaruf sinn aus.",
    305: "Basst, isch mach des Waschbrett sauber. Butz es inne mit ere Bürst.",
    308: "Des hab isch net mitkriegt. Weck misch nochemol.",
    309: "Do bist de ja, isch komm.",
    310: "Basst, isch fahr gleisch do weg.",
    311: "Die Wischtücher sinn runner.",
    314: "Des geht net. De kannst mer sage, isch soll misch umdrehe.",
    317: "Des geht grad net, isch mach e eigestellte Reinigung.",
    322: "Des kenn isch net. In de App stehe alle Sprachbefehle.",
    323: "Des kenn isch net. Frag misch emol, was isch alles kann.",
    324: "Isch wasch misch grad. Weck misch, wenn isch fertisch bin.",
    328: "Des kannst de mer nur sage, wenn isch grad saug.",
    338: "De Videoaaruf steht.",
    340: "Kaa Antwort.",
    341: "Do bist de ja. Isch geh der nach. Sag Enn, wenn es reischt.",
    342: "Wo bist de? Stell disch ungefähr annerthalb Meter vor misch.",
    343: "Isch hab disch verlore. De bist zu schnell. Stell disch annerthalb Meter vor misch.",
    364: "Isch risch de Videocode ei.",
    365: "Des Livebild is aus.",
    489: "Isch bin im Clean-Genius-Modus. Sag mer, isch soll uffhöre.",
    490: "Basst, eigestellte Reinigung: isch wisch.",
    491: "Basst, eigestellte Reinigung: isch saug.",
    511: "Isch mach grad nix.",
    512: "In de Kart is noch kaa Diermöbel. Trag es in de App ei.",
    513: "Basst, isch mach ums Diermöbel rum sauber.",
    516: "Isch guck, wo dei Viesch steckt.",
    517: "Isch hab es gefunne. Isch fahr zum Lade.",
    518: "Isch hab kaans gefunne. Isch fahr zum Lade.",
    522: "Was is denn schiefgange?",
    523: "Kannst de mer des e bissi genauer sage?",
    524: "Nimm misch dohie, wo es passiert is.",
    525: "Wart kurz, isch guck mer des aa.",
    641: "Sag mer aafach, isch soll mitm Sauge aafange.",
    642: "Sag mer aafach, isch soll stärker sauge.",
    643: "Sag mer aafach, isch soll mehr Wasser nemme.",
    644: "Sag mer aafach, isch soll sauge un wische.",
    645: "Sag mer aafach, isch soll wische.",
    646: "Sag mer aafach, isch soll dohie komme un sauber mache.",
    647: "Sag mer aafach, isch soll erst sauge un dann wische.",
    648: "Sag mer aafach, isch soll alles sauber mache.",
    659: "Des hab isch net verstanne. Frag misch emol, was isch alles kann.",
    694: "Sag mer aafach, isch soll mitm Sauge aafange.",

    # --- Erste Einrichtung ------------------------------------------------
    463: "Ei gude, schön dass de do bist. Mach de Deckel uff un scann de QR-Code.",
    464: "Damit später alles glatt läft, stell misch vorm Start uff die Station.",
    465: "Stell misch vorm Start uff die Station. Wenn de 'Isch lad uff' hörst, basst es.",
    466: "Mach bitte die Türe uff un räum de Bodde frei.",
    467: "Stell misch uff die Station un fang des Male neu aa.",
    468: "Guck der die Kart bitte in de App aa.",
    630: "Ei gude, schön dass de do bist. Mach de Deckel uff un scann de QR-Code.",
})

# --------------------------------------------------------------------------
# Die letzten Ansagen des r2532v (X50 Ultra Complete). Ihr Wortlaut steht in
# keiner Textdatei des Pakets - er wurde aus den deutschen Originalaufnahmen
# transkribiert (Windows-Spracherkennung) und anschliessend von Hand
# geglaettet. Sinngemaess richtig, im Wortlaut sinnvoll gekuerzt.
# --------------------------------------------------------------------------

TEXTE.update({
    24: 'Guck ma, ob der Wassertank richtisch dringsteckt.',
    101: 'Die Klapp von der Absaugstation is uff, oder der Beutel fehlt. Mach die Klapp zu oder leg en Beutel nei.',
    104: 'Es Waschbrett is net drin. Setz es nei un mach die Klammern uff beide Seite fest.',
    170: 'Die Tastesperr is aa. Halt die Taste an der Station gedrückt, dann gehts widder uff.',
    339: 'Anruf abgelehnt.',
    353: 'Der Schmutzwasserbehälter is drin.',
    354: 'Der Schmutzwasserbehälter is raus.',
    358: 'Setz bitte den Schmutzwasserbehälter nei.',
    386: 'Mei Schmutzwasserbehälter is voll. Isch fahr zurück un mach en leer.',
    387: 'Leermache is fertisch. Isch mach weider.',
    393: 'Mei Schmutzwasserbehälter is dreckisch. Mach en gleisch sauber.',
    394: 'Der Wassersensor will net mehr.',
    631: 'Schee, dass de disch für den Dreame entschiede hast. Mach die Klapp uff un scann den QR-Code, dann kannste die App lade.',
    634: 'Isch fang aa, die Haar zu entwirrn.',
    660: 'Sorry, des hab isch net verstanne. Sach Hey Rover, was kannst du, dann verzähl isch der, was isch alles kann.',
    664: 'Sach zu mer: Hey Rover, fang aa zu reinische.',
    665: 'Wenn alles passt, sach zu mer: Hey Rover, fang aa zu reinische.',
    666: 'Sach zu mer: Hey Rover, mach die Saugkraft stärker.',
    667: 'Sach zu mer: Hey Rover, gib mehr Wasser.',
    668: 'Sach zu mer: Hey Rover, fang aa zu sauge. Spaeder sachste wische, dann wechsel isch den Modus.',
    669: 'Sach zu mer: Hey Rover, fang aa zu wische. Spaeder kannste den Modus wechsele.',
    670: 'Sach zu mer: Hey Rover, komm her un mach do sauber.',
    671: 'Sach zu mer: Hey Rover, fang aa zu sauge. Spaeder kannste den Modus wechsele.',
    672: 'Sach zu mer: Hey Rover, fang aa zu reinische. Spaeder kannste die ganz Wohnung mache lasse.',
    674: 'Mei Mopp klemmt villeischt oder hat sisch was neigewickelt. Guck noch un mach en sauber.',
    682: 'Mei Mopp dreht sisch net mehr.',
    683: 'Der Mopp is net dro. Mach erst den Mopp dro un probiers dann nochema.',
    689: 'Isch fang aa, Staubbehälter un Beutel zu trockne.',
    690: 'Es Trockne von Staubbehälter un Beutel is gestoppt.',
    691: 'Der Mopp werd grad gewasche. Probiers spaeder nochema.',
    692: 'Isch fahr zum Lade. En extra Reinischung geht grad net.',
    696: 'Fehler an der Klapp.',
    697: 'Isch bin gesperrt. Mach erst die Kindersischerung aus.',
    698: 'Es Kartemale is fertisch. Isch find die Station net un fang selber aa zu reinische.',
    699: 'Sensorfehler. Guck noch, ob der Kamerasensor dreckisch is.',
    701: 'Die Platt is heiß. Bitte net aafasse.',
    702: 'Mit ere provisorische Kart kann isch net reinische. Drück nochema uff Reinischung, dann werd die Kart gespeischert.',
    703: 'Isch fang mit der Staub- un Mopptrocknung aa.',
    704: 'Die Mopptrocknung is pausiert.',
    706: 'Fehler am Kreisel. Bitte die Uffgab nochema starte.',
    707: 'Fehler am Fahrgestell. Bitte die Uffgab nochema starte.',
    708: 'Der Weg zur Ladestation is zu. Guck noch, ob was im Weg steht.',
    711: 'Die Desinfektion fängt aa.',
    712: 'Es Waschbrett is heiß. Bitte net aafasse.',
    715: 'In der Station fehlt der Mopp. Setz en nei, dann mach isch weider.',
    716: 'In der Station fehlt der Mopp. Setz en nei - solang schaff isch im Standardmodus.',
    717: 'Der Mopp sitzt net richtisch. Rück en zurescht, dann mach isch weider.',
    718: 'Des lässt sisch im Energiesparmodus net ännern. Mach den Energiesparmodus aus un probiers nochema.',
    719: 'Fehler beim Moppwechsel.',
    722: 'Der Mopp kommt in heiß Wasser, damit er warm werd. Drum dauerts en bissi länger. Hab en Moment Geduld.',
    723: 'Beim Kartemale guck, dass alles gut beleuscht is. Stell nix in die Türe un schieb weder misch noch die Station rum.',
    724: 'Der Mopp liegt in der Station net richtisch. Rück en gleisch zurescht.',
    725: 'Fehler an der Moppabdeckung.',
    726: 'Fehler am Rollmopp.',
    728: 'Isch fang mit der Bodepfleg aa.',
    729: 'Der Mopp werd grad gewechselt. Probiers spaeder nochema.',
    731: 'Mei Schmutzwassertank is voll. Stell misch zurück uff die Station, dass isch den Mopp wasche kann.',
    752: 'Isch mach mit der Bodepfleg weider.',
    754: 'Isch hab misch gefunne. Isch mach mit der Bodepfleg weider.',
    755: 'Der Lasersensor will net. Guck noch, ob do was dreckisch is oder klemmt.',
    757: 'Mei Schmutzwassertank is voll. Mach en gleisch leer.',
    758: 'Zu wenisch Wasser. Stell misch zurück uff die Station un drück uff Start, dann werd nochgefüllt.',
    765: 'Der Mopp werd grad gewechselt. Probiers spaeder nochema.',
    771: 'Der Rollmopp bleibt stehe oder is blockiert.',
    775: 'Solang der Mopp läuft, loss die Klapp zu.',
    777: 'Die Zeit is um. Guck noch, ob unnerm Gerät was im Weg is.',
    778: 'Achtung, pass uff dei Finger uff.',
    779: 'Die Zeit fürs Moppraushole is um. Isch hör uff.',
    780: 'Es Uffnehme oder Ablege vom Mopp hat net geklappt. Nimm den Mopp aus der Halterung un leg en widder ins Fach an der Klapp.',
    782: 'Fehler beim Uffflockern von der Roll. Mach se sauber, dann gehts weider.',
    784: 'Wenn Schritt eins fertisch is, fahr isch von alleen aus der Station.',
    785: 'Mach die Waschbrett-Basis bitte mit ere Bürst oder eme Tuch sauber. Danach tippste in der App uff Reinischung beende.',
    786: 'Die Waschbrett-Basis is sauber.',
    787: 'Isch fahr von alleen zur Station zurück un mach den Mopp sauber un trocke.',
    795: 'Isch fang mit der Reinischung von der Waschbrett-Basis aa. Des dauert ungefähr zwaa Minute.',
    797: 'Do stimmt villeischt was net mim Gerät. Ruf beim Kundendienst aa.',
    798: 'Die Selbstreinischung von der Station dauert ungefähr vier Minute. Schieb misch solang net rum.',
    799: 'Die Zeit is um. Guck noch, ob en Tier oder en Hindernis unnerm Gerät steht.',
    805: 'Isch fang aa, den grobe Dreck uffzusauge.',
    812: 'Stell misch bitte zum Lade in die Station.',
    813: 'Isch fang mit der kräftische Absaugung vom Dreck aa.',
    814: 'Isch fang mit der Selbstreinischung von der Station un der kräftische Absaugung aa.',
    823: "Der Wasserstand im Waschbrett passt net. Mach's sauber, eh's losgeht.",
    824: 'Der Rollmopp bleibt stehe oder is blockiert.',
    828: 'Der Filter is durch. Mach en bald sauber.',
    849: 'Isch fang aa, Staubbehälter un Beutel zu trockne.',
    850: 'Es Trockne von Staubbehälter un Beutel is gestoppt.',
    857: 'Setz bitte es Waschbrett nei.',
    910: 'Ei gude un willkomme in der Ausstellung für Saugroboter.',
    915: 'Der Wasserstand im Waschbrett passt net. Mach den Filter sauber, dann verstopft nix.',
})
